version: '2'

services:
  web:
    container_name: 'web'
    build: .
    depends_on: 
      - mongo
    ports: 
      - "4000:4000"
  mongo:
    container_name: "mongo"
    image: mongo
    ports: 
      - "27017:27017"